### ISSUE TITLE
Can we make Quinn Retina/HiDPI ready?

### ISSUE THREAD

**Issue by dennisquintel** [quintel/quinn#2]

**Comment by dennisquintel** [comment]
Difference between native elements and slider is evident on Retina display: ![](http://f.cl.ly/items/0o0q1o463O252F2N0c0s/Screen%20Shot%202013-02-15%20at%2011.11.02%20AM.png).

**Comment by antw** [comment]
@dennisschoenmakers Quinn does have HiDPI [images](https://github.com/quintel/quinn/blob/master/images/default-hidpi.png) and [stylesheets](https://github.com/quintel/quinn/blob/master/quinn.css#L180-L199); I think it's the custom image in our app which isn't. I'll dig out the original source file and make a HiDPI version.
